# Generated by Django 4.1.3 on 2022-11-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='address',
            field=models.TextField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
