# Generated by Django 4.1.3 on 2022-11-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_store', '0002_pizza_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Swallow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swallow_type', models.CharField(choices=[('A', 'Amala'), ('S', 'Semo'), ('P', 'Pounded Yam'), ('W', 'Wheat'), ('E', 'Eba')], max_length=1)),
            ],
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='topping1',
            new_name='soup',
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='topping2',
            new_name='swallow',
        ),
        migrations.AddField(
            model_name='pizza',
            name='phone_no',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pizza',
            name='address',
            field=models.CharField(max_length=255),
        ),
    ]
